# Traefik static configuration (v2)
entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

api:
  dashboard: true
  insecure: true  # ⚠️ à désactiver en prod ou planquer derrière une auth

log:
  level: DEBUG
